### ISSUE TITLE
A launcher icon is needed

### ISSUE THREAD

**Issue by AlinaStepanova** [AlinaStepanova/Lyrics#1]
A simple but beautiful launcher icon is needed

**Comment by graphicstone** [comment]
By launcher you mean Splash or Launcher Icon?

**Comment by EANimesha** [comment]
I can add a splash screen with a design. Assign me

**Comment by AlinaStepanova** [comment]
Hi, @graphicstone @EANimesha! Only the launcher icon is needed which will look good on both ios and android platforms and correspond to the existing design of the app. There is no need to create a splash screen. Please provide your ideas in pull requests and I will review them. Have a nice day!

**Comment by akhil2000mittal** [comment]
@AlinaStepanova do you have any specific idea or any icon can work?

**Comment by AlinaStepanova** [comment]
> @AlinaStepanova do you have any specific idea or any icon can work?

Hi @akhil2000mittal! I would say any icon but which will look good with the current design of the app (accent color, fonts, etc.)

**Comment by TheGiraffe** [comment]
Hello, I was wondering if I would be able to help with this as well?

**Comment by AlinaStepanova** [comment]
> Hello, I was wondering if I would be able to help with this as well?

Hi @TheGiraffe, feel free to provide your ideas in a pull request
